// <auto-generated />
namespace projekt_AK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migracja_pierwsza : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracja_pierwsza));
        
        string IMigrationMetadata.Id
        {
            get { return "201506191744425_migracja_pierwsza"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
