//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt_AK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projekt_AK.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afryka.
        /// </summary>
        public static string Afryka {
            get {
                return ResourceManager.GetString("Afryka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string Angielski {
            get {
                return ResourceManager.GetString("Angielski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeria.
        /// </summary>
        public static string Galeria {
            get {
                return ResourceManager.GetString("Galeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie.
        /// </summary>
        public static string Indie {
            get {
                return ResourceManager.GetString("Indie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś już zalogowany.
        /// </summary>
        public static string Jestes_zalogowany {
            get {
                return ResourceManager.GetString("Jestes_zalogowany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string Konto {
            get {
                return ResourceManager.GetString("Konto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu masz link do mojego repozytorium z projektem.
        /// </summary>
        public static string Link_repo {
            get {
                return ResourceManager.GetString("Link_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string Logowanie {
            get {
                return ResourceManager.GetString("Logowanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motoryzacja.
        /// </summary>
        public static string Motoryzacja {
            get {
                return ResourceManager.GetString("Motoryzacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamiłowanie do motoryzacji odziedziczyłem zapewne w genach gdyż od małego interesowałem się samochodami, gdy tylko troche podrosłem bardzo szybko zacząłem oglądać programy motoryzacyjne. Jeden z nich &quot;Top Gear&quot; po kilku odcinkach stał się moim ulubionym programem, ukazuję on samochody jako dzieła sztuki. Mazda 6 to samochód przedstawiony obok na zdjęciu, gdy tylko zobaczyłem go pod moim blokiem zakochałem się w nim od pierwszego wejrzenia, piękne linie nadwozia w połączeniu z całą sylwetką tworzą niesamowit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Motoryzacja_Opis {
            get {
                return ResourceManager.GetString("Motoryzacja_Opis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mnie.
        /// </summary>
        public static string O_mnie {
            get {
                return ResourceManager.GetString("O_mnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpis.
        /// </summary>
        public static string podpis {
            get {
                return ResourceManager.GetString("podpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podróże.
        /// </summary>
        public static string Podroze {
            get {
                return ResourceManager.GetString("Podroze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajlandia.
        /// </summary>
        public static string Podroze_Kraj {
            get {
                return ResourceManager.GetString("Podroze_Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednym z moich najskrytszych marzeń, jest wyjechanie do Tajlandii, której widoki są jednym z napiękniejszych miejsc na ziemi, cudowne krajobrazy, bogata kultura, egzotyczna kuchnia to wszystko skłania mnie tylko i wyłacznie do planowania swojej wyprawy marzeń..
        /// </summary>
        public static string Podroze_Opis {
            get {
                return ResourceManager.GetString("Podroze_Opis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pola herbaciane.
        /// </summary>
        public static string Pola_herbaciane {
            get {
                return ResourceManager.GetString("Pola_herbaciane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło i jego potwierdzenie nie pasują do siebie.
        /// </summary>
        public static string Pole_confirm_pasword_walidacja {
            get {
                return ResourceManager.GetString("Pole_confirm_pasword_walidacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole email jest wymagane.
        /// </summary>
        public static string Pole_email_jest_wymagane {
            get {
                return ResourceManager.GetString("Pole_email_jest_wymagane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość w polu Email nie jest prawidłowym adresem e-mail.
        /// </summary>
        public static string Pole_email_walidacja {
            get {
                return ResourceManager.GetString("Pole_email_walidacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole login jest wymagane.
        /// </summary>
        public static string Pole_login_jest_wymagane {
            get {
                return ResourceManager.GetString("Pole_login_jest_wymagane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Pole_login_walidacja {
            get {
                return ResourceManager.GetString("Pole_login_walidacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole password jest wymagane.
        /// </summary>
        public static string Pole_password_jest_wymagane {
            get {
                return ResourceManager.GetString("Pole_password_jest_wymagane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi mieć długość conajmniej 6 znaków.
        /// </summary>
        public static string Pole_password_walidacja {
            get {
                return ResourceManager.GetString("Pole_password_walidacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string Polski {
            get {
                return ResourceManager.GetString("Polski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string Rejestracja {
            get {
                return ResourceManager.GetString("Rejestracja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sawanna.
        /// </summary>
        public static string Sawanna {
            get {
                return ResourceManager.GetString("Sawanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Madryt.
        /// </summary>
        public static string Sport_Klub {
            get {
                return ResourceManager.GetString("Sport_Klub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportem zaraziłem sie od braci, którzy regularnie oglądają rozgrywki ekstraklasy. Bardzo lubię piłkę nożną, często znajdując wolną chwile spotykam się ze znajomymi aby pokopać piłkę. Jak każdy fan piłki nożnej mam swój ulubiony klub. Real Madryt, którego początki sięgają schyłku XIX wieku, najbardziej utytułowany klub wszechczasów. Miałem szczęście oglądać ere &quot;galacticos&quot; jako 10 latek. Jak sama nazwa wskazuje chodzi mi o największę gwiazdy futbolu, które grały w tamtych czasach. Był to piękny spektakl gdy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sport_Opis {
            get {
                return ResourceManager.GetString("Sport_Opis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stany Zjednoczone, Nowy York.
        /// </summary>
        public static string Stany_Zjednoczone {
            get {
                return ResourceManager.GetString("Stany_Zjednoczone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techniki.
        /// </summary>
        public static string Techniki {
            get {
                return ResourceManager.GetString("Techniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umiejętności.
        /// </summary>
        public static string Umiejetnosci {
            get {
                return ResourceManager.GetString("Umiejetnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyte techniki.
        /// </summary>
        public static string Użyte_techniki {
            get {
                return ResourceManager.GetString("Użyte_techniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        public static string Witaj {
            get {
                return ResourceManager.GetString("Witaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz_język.
        /// </summary>
        public static string Wybierz_język {
            get {
                return ResourceManager.GetString("Wybierz_język", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string Wyloguj {
            get {
                return ResourceManager.GetString("Wyloguj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymarzone podróże.
        /// </summary>
        public static string Wymarzone_podróże {
            get {
                return ResourceManager.GetString("Wymarzone_podróże", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Wyslij {
            get {
                return ResourceManager.GetString("Wyslij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij Wiadomość.
        /// </summary>
        public static string Wyślij_Wiadomość {
            get {
                return ResourceManager.GetString("Wyślij_Wiadomość", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyspy Phi Phi.
        /// </summary>
        public static string Wyspy_Phi_Phi {
            get {
                return ResourceManager.GetString("Wyspy_Phi_Phi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zainteresowania.
        /// </summary>
        public static string Zainteresowania {
            get {
                return ResourceManager.GetString("Zainteresowania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Zaloguj {
            get {
                return ResourceManager.GetString("Zaloguj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string Zamknij {
            get {
                return ResourceManager.GetString("Zamknij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string Zarejestruj {
            get {
                return ResourceManager.GetString("Zarejestruj", resourceCulture);
            }
        }
    }
}
